addqueue -c "a few minutes" -m 30 /usr/local/shared/python/2.7.6-gcc/bin/python resave.py 3
addqueue -c "a few minutes" -m 30 /usr/local/shared/python/2.7.6-gcc/bin/python resave.py 4
addqueue -c "a few minutes" -m 30 /usr/local/shared/python/2.7.6-gcc/bin/python resave.py 5
addqueue -c "a few minutes" -m 30 /usr/local/shared/python/2.7.6-gcc/bin/python resave.py 6
addqueue -c "a few minutes" -m 30 /usr/local/shared/python/2.7.6-gcc/bin/python resave.py 7
addqueue -c "a few minutes" -m 30 /usr/local/shared/python/2.7.6-gcc/bin/python resave.py 8
addqueue -c "a few minutes" -m 30 /usr/local/shared/python/2.7.6-gcc/bin/python resave.py 9
addqueue -c "a few minutes" -m 30 /usr/local/shared/python/2.7.6-gcc/bin/python resave.py 10
addqueue -c "a few minutes" -m 30 /usr/local/shared/python/2.7.6-gcc/bin/python resave.py 11
addqueue -c "a few minutes" -m 30 /usr/local/shared/python/2.7.6-gcc/bin/python resave.py 12
addqueue -c "a few minutes" -m 30 /usr/local/shared/python/2.7.6-gcc/bin/python resave.py 13
addqueue -c "a few minutes" -m 30 /usr/local/shared/python/2.7.6-gcc/bin/python resave.py 14
addqueue -c "a few minutes" -m 30 /usr/local/shared/python/2.7.6-gcc/bin/python resave.py 15
addqueue -c "a few minutes" -m 30 /usr/local/shared/python/2.7.6-gcc/bin/python resave.py 16
addqueue -c "a few minutes" -m 30 /usr/local/shared/python/2.7.6-gcc/bin/python resave.py 17
